### ISSUE TITLE
Record removed array items

### ISSUE THREAD

**Issue by dgwyer** [mikemcbride/uniq#2]
Thanks for this utility!

I'd like to be able to record which items are removed from the array. Would it be feasible to be able to optionally return two arrays? The first array with items removed and the second one containing only the removed items.

**Comment by mikemcbride** [comment]
@dgwyer hey, thanks! Sorry the for slow response! Things at work have been crazy lately. Yeah that would totally be possible. I don't think I'd want to do this by default since it would change the API, but we could add an optional parameter to return a second array with the duplicate items.

Would you expect the duplicate array to also be unique? For example, if you had these two arrays:

```js
const arr1 = [1,2,3]
const arr2 = [3,4,3,5]

const deduped = uniq([...arr1, ...arr2]) // [1,2,3,4,5]
```

It would have removed the value `3` twice... Would you expect the "duplicates" array to be `[3,3]` or just `[3]`? I'm leaning towards not having duplicate items in that array either.

**Comment by dgwyer** [comment]
Thanks for the response. Your proposed solution would work well. And I agree the removed duplicates should probably be unique too.
